### ISSUE TITLE
mechanical error compensation

### ISSUE THREAD

**Issue by dzario** [Paciente8159/uCNC#187]
Hi. 
I build my own CNC from polymer concrete 
[Photo](https://photos.app.goo.gl/WLovmMFLqDHvX3r19)
and I have some mechanical error , search CNC control 
system for software compensation.
Is possible do it with uCNC ?
3D printer marlin have Skew compensation .. Any idea?

**Comment by Paciente8159** [comment]
Marlin's skew compensation initial implementation was actually done by me. 😅 
That's part of the reason I stated µCNC.

Yes It's possible to do skew compensation, backlash compensation and use a planner strategy based on motors speed change and not axis (for machines with heavy mechanical moving parts) although there are not many tests performed over these 2 last features.

You are doing a polymer  concrete?? That's awesome. 👍

**Comment by dzario** [comment]
Hi . Perfect , when I will have more free time I check it.
I must better look what all support uCNC .
look at this photo album there are complete photo and video..
[https://photos.app.goo.gl/dBbXsZs1QvK7enkS8](url)
Polymer concrete part have key , and if complete all part to build CNC , then  
there is problem make any mechanical error correction .

Pls. give me link where I can read more about this correction , and backlash .. 

Best regards.

**Comment by Paciente8159** [comment]
Who much does that table weigh? That looks like a monster.

With ballbearing screw backlash Will be the least of your worries

**Comment by Paciente8159** [comment]
You can read more about some features in the [settings wiki](https://github.com/Paciente8159/uCNC/wiki/Basic-user-guide#%C2%B5cnc-configurations)

**Comment by dzario** [comment]
Hi. 
Complete machine around 160kg . 
I must read about your project .. you have plan to support for ESP32 ?

Thanks , best regards.

**Comment by Paciente8159** [comment]
ESP32 will probably be support but not now. For that you can check Bart's amazing [FluidNC ](https://github.com/bdring/FluidNC). It has tons of features and tools already built in. It also support up to 9 axis (all dual drive) I think.

To be honest besides AVR I never pushed the limits on the other MCU to see where they will top at. But if I can driver the atmega328p to near 40Khz I believe 32bit MCU will do at the very least 100Khz.

µCNC supports up to 6 axis, and you can dual drive 2 of them for self squaring machines.

**Comment by dzario** [comment]
Hi. Yes, I check FluidNC , but skew not support .. 
Is problem implement skew to kinematics ? I see your code .. not look very complicated ..
I will thinking about it ..
Thanks lot .. for your time .. 
Machine made from polymer concrete is very problematic solve some mechanical mistake..

Best regards.

**Comment by Paciente8159** [comment]
Yes I get the problem of the skew. What led me down this rabbit hole in the first place was on my 3d printer.
It add a bit of skew and noticeable when printing large parts with tight error margins.

If you need any help just let me know. The formula to fix skew is quite easy and is applied in and early stage after parsing the gcode command.

**Comment by Paciente8159** [comment]
By the way just did a quick test. With 3 axis all moving at the same time the STM32F4 tops out at about 130KHz.

**Comment by dzario** [comment]
Hi. Now I use EstlCam , very good software.
But I search alternative, GRBL is good idea .. but there some problem , Fluid NC is very easy and very cheap 
CNC controller with WiFi support , but also there are some problem. 
Start with uCNC , I need order new hardware ... etc .. .  I will see what I select.
Now must finish my polymer concrete machine.. and all measure .. how accurate is my CNC.
Then I will know what software need to use ..

regards.

**Comment by Paciente8159** [comment]
No problem. If you need any help just let me know.
FluidNC is a very good firmware and hardware is cheap. It's an excellent tool to go.
Also be sure to check [grblHAL](https://github.com/grblHAL). They have a ton of options and support many arm controllers. 
Did another quick test. Enabling 16-bit bresenham algorithm allow the STM32F4 to top at about 250KHz on 3 simultaneous axis.

**Comment by Paciente8159** [comment]
Just one note that is also important. Currently Stm32F4 does not store setting in ROM. The internal memory of this chip makes it some what inefficient to emulate Eeprom. Stm32F1 does not have this problem.

**Comment by dzario** [comment]
noted ..  I will contact you later ..

**Comment by dzario** [comment]
Hi. 
You have any forum or chat , where I can ask more question? 
This is not good place where I can talk with you or is ?

**Comment by dzario** [comment]
... I just have question .. for : 
1. scan surface and adapt gcode - auto leveling (PCB engrave)
2. new tool - length function 
3. run user script (in Marlin it is possible ) for example 20 or 30 gcode ..

... Now I don't use GRBL because , if use gcode with very small speed in long distance for example G01 X300 F5 .. then 
while not finish this command then not possible stop it .. and send new , etc .. your firmware can do this ? 
or jogging .. . jogging in GRBL is little problem..

regards

**Comment by Paciente8159** [comment]
About your questions:

scan surface and adapt gcode - auto leveling (PCB engrave)

- Can be done by external software in conjunction with µCNC or Grbl (example OpenCNCPilot or bCNC)

new tool - length function

- Both µCNC and Grbl support Tool Length Offset.

run user script (in Marlin it is possible ) for example 20 or 30 gcode

- µCNC as a built in extension module that allows to create custom G/M codes. Some knowledge of C is required. 

support native for example i2c oled LCD SSD1306 similar where will see all important information..

- Neither Grbl or µCNC support LCD. There are some options of external controllers and displays that can work has a GrblGUI and connect directly to a Grbl board. If the idea is only to show info about the machine µCNC extension module might also be used to create custom module for this purpose. Additional external libraries might be needed (like u8g2) 

... Now I don't use GRBL because , if use gcode with very small speed in long distance for example G01 X300 F5 .. then
while not finish this command then not possible stop it .. and send new , etc .. your firmware can do this ?

- If you are sending the command manually yes it's possible. You send G01 X300 F5. The moment you want to stop send Hold command to do a controlled stop. After this if you do a soft-reset  the command is flushed and you can send another command.
- If you are using a gcode sender reading from a file then no it's not possible because most gcode senders try to send as many gcode commands at once to keep the buffers filled so the controller can calculate motion speed as optimally as it can.

or jogging .. . jogging in GRBL is little problem..

- Jogging is the same as Grbl. It will only be possible to jog when machine is not running any program. This is actually one of those things I want to make in µCNC is to be able to jog in the middle of a user pause in the program. But I have not yet implemented this.

**Comment by dzario** [comment]
Thanks.
